# Generated by Django 2.1.2 on 2018-11-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='customer',
            field=models.CharField(max_length=255),
        ),
    ]
