# Generated by Django 2.1.2 on 2018-11-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20181119_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
