# Generated by Django 2.1.2 on 2019-01-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20190129_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_model',
            new_name='books_name',
        ),
    ]
