# Generated by Django 2.1.2 on 2019-02-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20190130_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='topic_one',
        ),
    ]
